export const user = {
  userId: "",
  username: "",
  signupDate: "",
  profilePicture: <img src="" alt="" />,
  phoneNumber: "",
  location: "",
  range: "",
  email: "",
};

export const availableItems = [
  {
    item: "Pineapple",
    quantity: 1,
    location: "SW109FL",
    additionalInformation: null,
    userId: 5,
    itemId: 70,
  },
  {
    item: "Chestnuts",
    quantity: "1 kg",
    location: "SW109FL",
    additionalInformation: null,
    userId: 5,
    itemId: 71,
  },
  {
    item: "Oranges",
    quantity: 5,
    location: "SW109FL",
    additionalInformation: null,
    userId: 5,
    itemId: 72,
  },
  {
    item: "Eggs",
    quantity: 6,
    location: "N18PJ",
    additionalInformation: null,
    userId: 90,
    itemId: 73,
  },
  {
    item: "Bread",
    quantity: "2 loaves",
    location: "NW6 8LN",
    additionalInformation: "Contains seeds",
    userId: 8,
    itemId: 74,
  },
  {
    item: "Parsnips",
    quantity: "1 kg",
    location: "SW89LO",
    additionalInformation: null,
    userId: 12,
    itemId: 75,
  },
  {
    item: "Lettuce",
    quantity: 2,
    location: "SW89LO",
    additionalInformation: null,
    userId: 12,
    itemId: 76,
  },
  {
    item: "Raisins",
    quantity: "350 g",
    location: "SW89LO",
    additionalInformation: null,
    userId: 12,
    itemId: 77,
  },
];
